spring:
  datasource:
    url: jdbc:mysql://localhost:3306/content_center?serverTimezone=GMT%2B8
    hikari:
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
#        namespace: 948ea1d8-4d45-46c0-85ba-0bd09d4244c3
        cluster-name: NJ
    sentinel:
#      transport:
#        dashboard: localhost:8080
      filter:
        #打开对spring mvc端点的保护
        enabled: true
#      web-context-unify: false
    stream:
      rocketmq:
        binder:
          name-server: localhost:9876
        bindings:
          output:
            producer:
              transactional: true
              group: tx-add-bonus-group
      bindings:
        output:
          destination: add-bonus
#        my-output:
#          destination: stream-my-topic
  application:
    name: content-center
  main:
    allow-bean-definition-overriding: true
server:
  port: 8010

ribbon:
  eager-load:
    enabled: true
    clients: user-center
#user-center:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
logging:
  level:
    com.guanshi.contentcenter.feignclient.UserCenterFeignClient: debug
    com.alibaba.nacos: error

feign:
#  sentinel:
#    enabled: true
  client:
    config:
      default:
        logger-level: FULL
        request-interceptors:
          - com.guanshi.contentcenter.feignclient.interceptor.TokenRelayRequestInterceptor
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50
  sentinel:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

resttemplate:
  sentinel:
    # 设置成false，表示关闭@SentinelRestTemplate注解
    enabled: true

jwt:
  secret: aksdbkasdhglashdlghfalsdhflahdls
  # 有效期，单位秒，默认2周
  expire-time-in-second: 1209600

#ahas:
#  license: 324e4dd8d49d4f83ad08e54d095e73f2
#  namespace: default
#project.name: content-center
#rocketmq:
#  name-server: localhost:9876
#  producer:
#    group: test-group




