spring:
  datasource:
    url: jdbc:mysql://localhost:3306/content_center?serverTimezone=UTC
    hikari:
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
#        namespace: 948ea1d8-4d45-46c0-85ba-0bd09d4244c3
        cluster-name: BJ
    sentinel:
      transport:
        dashboard: localhost:8080
      filter:
        #打开对spring mvc端点的保护
        enabled: true
#      web-context-unify: false
    stream:
      rocketmq:
        binder:
          name-server: localhost:9876


  application:
    name: content-center
  main:
    allow-bean-definition-overriding: true
server:
  port: 8010

ribbon:
  eager-load:
    enabled: true
    clients: user-center
#user-center:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
logging:
  level:
    com.guanshi.contentcenter.feignclient.UserCenterFeignClient: debug

feign:
  client:
    config:
      default:
        logger-level: BASIC
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50
  sentinel:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'


#resttemplate:
#  sentinel:
#    enabled: false
#ahas:
#  license: 324e4dd8d49d4f83ad08e54d095e73f2
#  namespace: default
#project.name: content-center





